/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_zarr_bloscjava_Blosc */

#ifndef _Included_dev_zarr_bloscjava_Blosc
#define _Included_dev_zarr_bloscjava_Blosc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_zarr_bloscjava_Blosc
 * Method:    _compress
 * Signature: ([BIIIILjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_zarr_bloscjava_Blosc__1compress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jstring, jint);

/*
 * Class:     dev_zarr_bloscjava_Blosc
 * Method:    _decompress
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_zarr_bloscjava_Blosc__1decompress
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
